### ISSUE TITLE
感谢作者做出这么好的插件

### ISSUE THREAD

**Issue by supermebing** [yanhao98/baidu_ocr_plugin#1]
能否增加一个银行卡识别的功能  目前身份证确实好用

**Comment by yanhao98** [comment]
> 能否增加一个银行卡识别的功能 目前身份证确实好用

我抽时间看一下。

**Comment by supermebing** [comment]
感谢作者 没想到这么快回复  我刚才打开看了一下 本来想自己修改一下看能否实现的   我高估自己了

**Comment by yanhao98** [comment]
发布了1.0.2版本。
https://pub.dev/packages/baidu_ocr_plugin/changelog

身份证是支持扫描识别的。银行卡我看好像官网demo也不支持扫描识别。
