### ISSUE TITLE
ios端无法正常运行

### ISSUE THREAD

**Issue by InTheClodus** [yanhao98/baidu_ocr_plugin#2]
![6E410358-A6E7-4B93-9A89-55C573D762AE](https://user-images.githubusercontent.com/33110499/189480724-33174c59-44a5-407f-8998-f466ffbc7671.png)

这是报错内容基本截图，不知道您是否有时间帮忙看看

**Comment by yanhao98** [comment]
> ![6E410358-A6E7-4B93-9A89-55C573D762AE](https://user-images.githubusercontent.com/33110499/189480724-33174c59-44a5-407f-8998-f466ffbc7671.png)
> 
> 这是报错内容基本截图，不知道您是否有时间帮忙看看

file is universal (armv7,arm64) but does not contain the x86 64 architecture: 
这个应该是不支持模拟器架构。
