### ISSUE TITLE
图片裁剪问题

### ISSUE THREAD

**Issue by hycinth** [yanhao98/baidu_ocr_plugin#4]
拍照和相册选取图片后回裁剪图片，怎么设置去掉这一步或着设置裁剪框的默认大小？

**Comment by yanhao98** [comment]
暂时不支持。支持后给你回复。

**Comment by yanhao98** [comment]
2.0.2版本支持了传入图片二进制数据进行识别。你可以自己以其他任意方式处理图片然后拿到图片二进制数据来识别。具体看一下示例项目。
